#!/bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

# Compositor for transparency (no need now, maybe for trayer)
#compton &

# Set the wallpaper
feh --bg-fill ~/.config/wallpaper.jpg &

# Bar : Add a polybar on the rigth top (finally deactivate, not need)
#polybar righttopbar &

# Notifications : dunst or deadd (to test / configure it)
#dunst &

# System Tray : trayer or stalonetray (to test / configure it)
#trayer &

# Set Screen saver afer 2 min and Lock after screensaver launched
xset s 120 &
light-locker --lock-after-screensaver 1 &

# For keep authentication on mounting network drive
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &


#Fix problem for java application
wmname LG3D &

# Bsp Monitor
bspc monitor -d 1 2 3 4 5

# Bsp Desktop
bspc desktop 2 --layout monocle

# Bsp Config
bspc config border_width         4
bspc config window_gap           8
bspc config automatic_scheme     alternate

# Bspc Rule
# Desktop 1 : Web Browser
bspc rule -a Firefox-esr desktop=1 follow=on

# Desktop 2 : Work (generally full screen apps like IDE)
bspc rule -a jetbrains-idea-ce desktop=2 follow=on
bspc rule -a cura desktop=2 follow=on
bspc rule -a digikam desktop=2 follow=on

# Desktop 3 : File Manager
bspc rule -a Thunar desktop=3 follow=on
bspc rule -a URxvt:lf desktop=3 follow=on
bspc rule -a Zathura state=tiled 

# Desktop 4 : Mail / Chat Client
bspc rule -a thunderbird desktop=4 follow=on

# Desktop 5 : Music Player / Torrent Client (Background tools)
bspc rule -a Transmission-gtk desktop=5 follow=on
bspc rule -a URxvt:htop desktop=5 follow=on

# Script for lf to set preview only on focus
~/.config/lf/lf-preview-only-on-focus.sh &
